### ISSUE TITLE
Rethink data structure

### ISSUE THREAD

**Issue by leonlarsson** [leonlarsson/cs-case-sim#1]
It's a mess. Local storage vs API vs DB....

**Comment by leonlarsson** [comment]
Specific local storage type has been killed

**Comment by leonlarsson** [comment]
It's ok

**Comment by BadMachine** [comment]
@leonlarsson have never seen a person talking to himself in github issues

**Comment by leonlarsson** [comment]
> @leonlarsson have never seen a person talking to himself in github issues

I am insane
